### ISSUE TITLE
REQUEST: Spotify Badge Color Change

### ISSUE THREAD

**Issue by WrathChaos** [sndrjhlncgr/README-Spotify-Status#3]
Hello @sndrjhlncgr,
First of all, really awesome work man! Thank you :) 

I just want to change the Spotify badge colour, is that possible? 

Also, I have a suggestion for this project. I believe that the setup of the usage should be easier. This example is a lot easier if you can do something like this one. I think more people will use yours :) 

https://github.com/kittinan/spotify-github-profile

Thanks a lot for the project tho!

**Comment by sndrjhlncgr** [comment]
Good day @WrathChaos. about in changing the spotify badge colour. i already working on that, and thankyou for ur suggestion about the setup. i will do it! godbless sir!

**Comment by WrathChaos** [comment]
Thank you so much for the quick response @sndrjhlncgr  :)

Can you also help me with the update the already using vercel environments? I simply put a new environment with the new badge name, re-deploy it but still, it does not change. What should I do about this?

**Comment by sndrjhlncgr** [comment]
![dsadasdasdadasdas](https://user-images.githubusercontent.com/51398549/105972639-ca5fd000-60c6-11eb-9ab2-e2d612f07705.png)

choose the secret type environment then create a new secret. and redeploy it.

**Comment by WrathChaos** [comment]
Still could not change but whatever :) Thank you
