### ISSUE TITLE
sh: jekyll: command not found

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [sndrjhlncgr/README-Spotify-Status#4]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/5072806/108975464-ceabe880-7686-11eb-9be8-abdc65a4e686.png">

How can I solve this issues? I did the exact steps as in your README.md

**Comment by mariomurrent-softwaresolutions** [comment]
Nevermind - my mistake

**Comment by Nithin552** [comment]
hey...i encountered the same error how did you deal with it?? plz help

**Comment by mariomurrent-softwaresolutions** [comment]
Take care on the deployment what kind of project you are using

**Comment by Nithin552** [comment]
https://github.com/sndrjhlncgr/README-Spotify-Status this..

**Comment by Nithin552** [comment]
added all env variables but when deploying getting the jekyll related errors as you mentioned above

**Comment by mariomurrent-softwaresolutions** [comment]
https://camo.githubusercontent.com/dbdaa60a8b9d1f88b8ce5dc72874882002416f07856855be1aa08b2e1bc5bbbe/68747470733a2f2f692e6962622e636f2f7676357a3479502f556e7469746c65642e706e67

Be sure you take 'Other'

**Comment by Nithin552** [comment]
thanks will give a try & let you know

**Comment by Nithin552** [comment]
thanks it got deployed successfully..

**Comment by mariomurrent-softwaresolutions** [comment]
What was the error?
